const products = [
  {
    _id: "1",
    name: "Groceries",
    image: "/images/groceries.jpg",
    description: "Fresh fruits and vegetables",
    category: "products",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numRevies: 12,
  },
  {
    _id: "2",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "products",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numRevies: 12,
  },
  {
    _id: "3",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "products",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numRevies: 12,
  },
  {
    _id: "4",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "products",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numRevies: 12,
  },
  {
    _id: "5",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "products",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numRevies: 12,
  },
  {
    _id: "6",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "products",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numRevies: 12,
  },
  {
    _id: "7",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "products",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numRevies: 12,
  },
  {
    _id: "8",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "products",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numRevies: 12,
  },
];

export default products;
