const products = [
  {
    _id: "1",
    name: "Groceries and some random text to test the elipsis feature",
    image: "/images/groceries.jpg",
    description: "Fresh fruits and vegetables",
    category: "spices",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 11,
  },
  {
    _id: "2",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "fruits",
    price: 100,
    countInStock: 10,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "3",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "vegetables",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "food-grain",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "oils",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "6",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "bakery",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "7",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "non-veg",
    price: 100,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "8",
    name: "apple",
    image: "/images/fruits_vegetables.jpg",
    description: "Fresh fruits and vegetables",
    category: "snacks",
    price: 100,
    countInStock: 0,
    rating: 4.5,
    numReviews: 12,
  },
];

export default products;
